### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by fedepare** [Huizerd/evolutionary#2]
The multiprocessing package is throwing the following error when running main.py (even with processes=1):

```
Traceback (most recent call last):
  File "main.py", line 292, in <module>
  File "main.py", line 91, in main
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
  File "/home/fede/.local/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
RuntimeError: unable to open shared memory object </torch_8033_2588382653> in read-write mode
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
OSError: [Errno 24] Too many open files: '/usr/lib/python3/dist-packages/apport/__init__.py'

Original exception was:
Traceback (most recent call last):
  File "main.py", line 292, in <module>
  File "main.py", line 91, in main
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
  File "/home/fede/.local/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
RuntimeError: unable to open shared memory object </torch_8033_2588382653> in read-write mode
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
  File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
  File "/usr/lib/python3.6/shutil.py", line 482, in rmtree
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/pymp-lvhtjcav'
```

Any idea about it?

**Comment by fedepare** [comment]
Related: https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu

**Comment by fedepare** [comment]
Hypothesis: The issue may come from deap, the evolutionary package

**Comment by fedepare** [comment]
This solved the issue:

![image](https://user-images.githubusercontent.com/17462626/88662870-e1ebdb00-d0da-11ea-84be-6442b3266d82.png)
